development:
  secret_key_base: run rake secret
  google_client_id: from google developer console
  google_client_secret: from google developer console
  facebook_app_id: from facebook developer dashboard
  facebook_app_secret: from facebook developer dashboard

test:
  secret_key_base: run rake secret

production:
  secret_key_base: run rake secret
  google_client_id: from google developer console
  google_client_secret: from google developer console
  facebook_app_id: from facebook developer dashboard
  facebook_app_secret: from facebook developer dashboard
